const CONTENT = [
  {
    id: 1,
    type: "movie",
    title: "Intercambiados",
    year: 2026,
    director: "Nathan Greno",
    runtime: 102,
    country: "United States of America",
    synopsis:
      "Una pequeña criatura del bosque y un ave majestuosa intercambian cuerpos. Ahora, deben aliarse para sobrevivir a la aventura más salvaje de sus vidas.",
    poster: "https://image.tmdb.org/t/p/w400/m0psah5Ttchm7Jlp74NZ5xDe6C8.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Michael B. Jordan",
      "Juno Temple",
      "Tracy Morgan",
      "Cedric the Entertainer",
      "Justina Machado",
    ],
    releaseDate: "2026-05-01",
    studio: "Skydance Animation",
    genres: ["Aventura", "Animación", "Familia", "Fantasía"],
    rating: 4.4,
  },
  {
    id: 2,
    type: "movie",
    title: "Sueño de fuga",
    year: 1994,
    director: "Frank Darabont",
    runtime: 143,
    country: "United States of America",
    synopsis:
      "Andy Dufresne es un banquero injustamente encarcelado en la prisión de Shawshank por el asesinato de su esposa y su amante. Dentro de prisión, Andy entabla una amistad con Red, un prisionero con habilidades para conseguir cosas. Estos dos hombres encarcelados se unirán durante años, encontrando consuelo y eventual redención a través de actos de decencia común.",
    poster: "https://image.tmdb.org/t/p/w400/l6V3TEoJlGh3ztAFxK2hemHfDJ2.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Tim Robbins",
      "Morgan Freeman",
      "Bob Gunton",
      "William Sadler",
      "Clancy Brown",
    ],
    releaseDate: "1994-09-23",
    studio: "Castle Rock Entertainment",
    genres: ["Drama", "Crimen"],
    rating: 4.3,
  },
  {
    id: 3,
    type: "movie",
    title: "El Padrino",
    year: 1972,
    director: "Francis Ford Coppola",
    runtime: 175,
    country: "United States of America",
    synopsis:
      "Don Vito Corleone es el respetado y temido jefe de una de las cinco familias de la mafia de Nueva York. Tiene cuatro hijos: una chica, Connie, y tres varones: el impulsivo Sonny, el pusilánime Freddie y Michael, que no quiere saber nada de los negocios de su padre. Cuando Corleone, siempre aconsejado por su consejero Tom Hagen, se niega a intervenir en el negocio de las drogas, el jefe de otra banda ordena su asesinato. Empieza entonces una violenta y cruenta guerra entre las familias mafiosas.",
    poster: "https://image.tmdb.org/t/p/w400/tUeZeWzbw37sOIpDsuK8qq8Unor.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Marlon Brando",
      "Al Pacino",
      "James Caan",
      "Robert Duvall",
      "Richard S. Castellano",
    ],
    releaseDate: "1972-03-14",
    studio: "Paramount Pictures",
    genres: ["Drama", "Crimen"],
    rating: 4.3,
  },
  {
    id: 4,
    type: "movie",
    title: "Proyecto Fin del Mundo",
    year: 2026,
    director: "Phil Lord",
    runtime: 156,
    country: "United States of America",
    synopsis:
      "El profesor de ciencias Ryland Grace despierta en una nave espacial a años luz de su hogar sin recordar quién es ni cómo llegó allí. A medida que recupera la memoria, comienza a descubrir su misión: resolver el enigma de la misteriosa sustancia que está causando la extinción del sol.",
    poster: "https://image.tmdb.org/t/p/w400/cWpvRQcppLnXD0Kno4OZUzkA05R.jpg",
    trailer: "https://www.youtube.com/embed/S7w4cDtHyFQ",
    cast: [
      "Ryan Gosling",
      "Sandra Hüller",
      "James Ortiz",
      "Lionel Boyce",
      "Milana Vayntrub",
    ],
    releaseDate: "2026-03-15",
    studio: "Lord Miller",
    genres: ["Ciencia ficción", "Aventura"],
    rating: 4.2,
  },
  {
    id: 5,
    type: "movie",
    title: "El Padrino II",
    year: 1974,
    director: "Francis Ford Coppola",
    runtime: 202,
    country: "United States of America",
    synopsis:
      "Continuación de la historia de los Corleone por medio de dos historias paralelas: la elección de Michael como jefe de los negocios familiares y los orígenes del patriarca, Don Vito Corleone, primero en su Sicilia natal y posteriormente en Estados Unidos, donde, empezando desde abajo, llegó a ser un poderosísimo jefe de la mafia de Nueva York.",
    poster: "https://image.tmdb.org/t/p/w400/nitJxV5GfaOB44VVOpVx2fOxnuT.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Al Pacino",
      "Robert Duvall",
      "Diane Keaton",
      "Robert De Niro",
      "John Cazale",
    ],
    releaseDate: "1974-12-20",
    studio: "Paramount Pictures",
    genres: ["Drama", "Crimen"],
    rating: 4.2,
  },
  {
    id: 6,
    type: "movie",
    title: "La Lista de Schindler",
    year: 1993,
    director: "Steven Spielberg",
    runtime: 195,
    country: "United States of America",
    synopsis:
      "La emotiva y desgarradora historia real de Oskar Schindler, un empresario alemán que, durante el Holocausto, emplea a judíos en su fábrica para salvarlos del exterminio nazi, mostrando cómo un acto de compasión puede desafiar el horror y la barbarie.",
    poster: "https://image.tmdb.org/t/p/w400/3Ho0pXsnMxpGJWqdOi0KDNdaTkT.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Liam Neeson",
      "Ben Kingsley",
      "Ralph Fiennes",
      "Caroline Goodall",
      "יהונתן סגל",
    ],
    releaseDate: "1993-12-15",
    studio: "Amblin Entertainment",
    genres: ["Drama", "Historia", "Bélica"],
    rating: 4.2,
  },
  {
    id: 7,
    type: "movie",
    title: "12 Hombres en Pugna",
    year: 1957,
    director: "Sidney Lumet",
    runtime: 96,
    country: "United States of America",
    synopsis:
      "Doce miembros de un jurado deliberan sobre el veredicto de un caso de homicidio. A medida que discuten, los prejuicios personales y las opiniones en conflicto emergen, desafiando la justicia y revelando la complejidad del sistema legal.",
    poster: "https://image.tmdb.org/t/p/w400/andXPjcmwHstD4zFccFlOKMgoBh.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Martin Balsam",
      "John Fiedler",
      "Lee J. Cobb",
      "E.G. Marshall",
      "Jack Klugman",
    ],
    releaseDate: "1957-04-10",
    studio: "Orion-Nova Productions",
    genres: ["Drama"],
    rating: 4.2,
  },
  {
    id: 8,
    type: "movie",
    title: "Criaturas luminosas",
    year: 2026,
    director: "Olivia Newman",
    runtime: 114,
    country: "United States of America",
    synopsis:
      "Mientras trabaja por las noches en un pequeño acuario, una viuda forja un vínculo con un pulpo inteligente y un joven sin rumbo en este emotivo drama basado en la exitosa novela.",
    poster: "https://image.tmdb.org/t/p/w400/aNixJoh0U4kN85YM6vPyVZL6ALF.jpg",
    trailer: "https://www.youtube.com/embed/o2YgAKPK5HE",
    cast: [
      "Sally Field",
      "Lewis Pullman",
      "Colm Meaney",
      "Alfred Molina",
      "Joan Chen",
    ],
    releaseDate: "2026-05-07",
    studio: "Anonymous Content",
    genres: ["Drama", "Misterio"],
    rating: 4.2,
  },
  {
    id: 9,
    type: "movie",
    title: "El viaje de Chihiro",
    year: 2001,
    director: "Hayao Miyazaki",
    runtime: 125,
    country: "Japan",
    synopsis:
      "Durante la mudanza de su familia a los suburbios, una huraña niña de 10 años de edad deambula por un mundo gobernado por dioses, brujas y espíritus, y donde los humanos se convierten en bestias.",
    poster: "https://image.tmdb.org/t/p/w400/2RcxjDykOssx4SfqshewyI9vfSl.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: ["柊瑠美", "入野自由", "夏木マリ", "内藤剛志", "沢口靖子"],
    releaseDate: "2001-07-20",
    studio: "Studio Ghibli",
    genres: ["Animación", "Familia", "Fantasía"],
    rating: 4.2,
  },
  {
    id: 10,
    type: "movie",
    title: "Batman: El caballero de la noche",
    year: 2008,
    director: "Christopher Nolan",
    runtime: 152,
    country: "United Kingdom",
    synopsis:
      "Cuando la amenaza conocida como el Joker causa estragos y caos en la gente de Ciudad Gótica, Batman debe aceptar una de las mayores pruebas psicológicas y físicas de su capacidad para luchar contra la injusticia.",
    poster: "https://image.tmdb.org/t/p/w400/vLFCrzI3V4kbze877tP1H7TqppL.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Christian Bale",
      "Heath Ledger",
      "Aaron Eckhart",
      "Michael Caine",
      "Maggie Gyllenhaal",
    ],
    releaseDate: "2008-07-16",
    studio: "Warner Bros. Pictures",
    genres: ["Acción", "Crimen", "Suspense"],
    rating: 4.2,
  },
  {
    id: 11,
    type: "movie",
    title: "Amor Contra Viento Y Marea",
    year: 1995,
    director: "Aditya Chopra",
    runtime: 190,
    country: "India",
    synopsis:
      "Los Singh son una familia india con grandes convicciones culturales de su nación de origen, que emigraron a Reino Unido antes de nacer sus primeros hijos. Uno de ellos querrá casarse con una mujer ajena a su cultura y para ello deberá hacer todos los esfuerzos por convencer a su familia.",
    poster: "https://image.tmdb.org/t/p/w400/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
    trailer: "https://www.youtube.com/embed/OjATPq2UTtU",
    cast: [
      "Kajol",
      "शाहरुख़ ख़ान",
      "Amrish Puri",
      "Farida Jalal",
      "Anupam Kher",
    ],
    releaseDate: "1995-10-20",
    studio: "Yash Raj Films",
    genres: ["Comedia", "Drama", "Romance"],
    rating: 4.2,
  },
  {
    id: 12,
    type: "movie",
    title: "Milagros Inesperados",
    year: 1999,
    director: "Frank Darabont",
    runtime: 189,
    country: "United States of America",
    synopsis:
      "Las vidas de los guardias del corredor de la muerte se ven afectadas por uno de sus cargos: un hombre negro acusado de asesinato y violación de niños, pero que tiene un misterioso don.",
    poster: "https://image.tmdb.org/t/p/w400/7ezlnHDn6clFku58TmFmpKUQUqf.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Tom Hanks",
      "David Morse",
      "Bonnie Hunt",
      "Michael Clarke Duncan",
      "James Cromwell",
    ],
    releaseDate: "1999-12-10",
    studio: "Castle Rock Entertainment",
    genres: ["Fantasía", "Drama", "Crimen"],
    rating: 4.2,
  },
  {
    id: 13,
    type: "movie",
    title: "El señor de los anillos: El retorno del rey",
    year: 2003,
    director: "Peter Jackson",
    runtime: 202,
    country: "New Zealand",
    synopsis:
      "Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de que se decida el destino de la Tierra Media, y por primera vez en mucho tiempo, parece que hay una pequeña esperanza. La atención del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, y del cual Aragorn tendrá que reclamar el trono para ocupar su puesto de rey.",
    poster: "https://image.tmdb.org/t/p/w400/mWuFbQrXyLk2kMBKF9TUPtDwuPx.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Elijah Wood",
      "Ian McKellen",
      "Viggo Mortensen",
      "Sean Astin",
      "Andy Serkis",
    ],
    releaseDate: "2003-12-17",
    studio: "New Line Cinema",
    genres: ["Aventura", "Fantasía", "Acción"],
    rating: 4.2,
  },
  {
    id: 14,
    type: "movie",
    title: "¿Quieres ser mi hijo?",
    year: 2023,
    director: "Ihtzi Hurtado",
    runtime: 100,
    country: "United States of America",
    synopsis:
      "Lu, una mujer conformista de 40 años, un día descubre que su pareja de hace 15 años la estaba engañando. Conoce a su nuevo vecino Javier, un joven y apuesto mujeriego de tan sólo 23 años. Para conseguir el trabajo de sus sueños, Lu decide mentir en su entrevista diciendo que tiene un hijo de 19 años, y le ofrece el trabajo a Javier para que se haga pasar por su hijo.",
    poster: "https://image.tmdb.org/t/p/w400/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg",
    trailer: "https://www.youtube.com/embed/0GpYVWW0b-8",
    cast: [
      "Ludwika Paleta",
      "Juanpa Zurita",
      "Hernán Mendoza",
      "Harold Azuara",
      "Agustín Arana",
    ],
    releaseDate: "2023-09-21",
    studio: "MarVista Entertainment",
    genres: ["Comedia", "Romance"],
    rating: 4.2,
  },
  {
    id: 15,
    type: "movie",
    title: "Parásitos",
    year: 2019,
    director: "Bong Joon Ho",
    runtime: 132,
    country: "South Korea",
    synopsis:
      "Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a recibir clases particulares en casa de Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, comienzan una interrelación de resultados imprevisibles.",
    poster: "https://image.tmdb.org/t/p/w400/4N55tgxDW0RRATyrZHbx0q9HUKv.jpg",
    trailer: "https://www.youtube.com/embed/broPd_xWuTw",
    cast: ["송강호", "이선균", "Cho Yeo-jeong", "Choi Woo-shik", "박소담"],
    releaseDate: "2019-05-30",
    studio: "Barunson E&A",
    genres: ["Comedia", "Suspense", "Drama"],
    rating: 4.2,
  },
  {
    id: 16,
    type: "series",
    title: "Off Campus",
    year: 2026,
    director: "Gina Fattore",
    runtime: 0,
    country: "United States of America",
    synopsis:
      "Hannah Wells acepta darle clases particulares a Garrett Graham, el capitán del equipo de hockey, para conquistar al chico que le gusta. Lo que empieza como un simple acuerdo se convierte en una conexión real mientras ambos enfrentan su pasado.",
    poster: "https://image.tmdb.org/t/p/w400/pI4sEVVbswtyOL2uaFxZs2tPOnQ.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Ella Bright",
      "Belmont Cameli",
      "Mika Abdalla",
      "Stephen Kalyn",
      "Jalen Thomas Brooks",
    ],
    releaseDate: "2026-05-13",
    studio: "Amazon MGM Studios",
    genres: ["Drama"],
    rating: 4.5,
  },
  {
    id: 17,
    type: "series",
    title: "Breaking Bad",
    year: 2008,
    director: "Vince Gilligan",
    runtime: 0,
    country: "United States of America",
    synopsis:
      "Un profesor de Química de secundaria con cáncer terminal se asocia a un exestudiante para asegurar el futuro de su familia al fabricar y vender metanfetamina.",
    poster: "https://image.tmdb.org/t/p/w400/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    trailer: "https://www.youtube.com/embed/mXd1zTwcQ18",
    cast: [
      "Bryan Cranston",
      "Aaron Paul",
      "Anna Gunn",
      "RJ Mitte",
      "Dean Norris",
    ],
    releaseDate: "2008-01-20",
    studio: "Sony Pictures Television",
    genres: ["Drama", "Crimen"],
    rating: 4.4,
  },
  {
    id: 18,
    type: "series",
    title: "Frieren: Más allá del final del viaje",
    year: 2023,
    director: "Varios",
    runtime: 25,
    country: "Japan",
    synopsis:
      "Décadas después de que su grupo derrotara al Rey Demonio, el funeral de un viejo amigo lleva a la hechicera elfa Frieren a embarcarse en un viaje de autodescubrimiento.",
    poster: "https://image.tmdb.org/t/p/w400/6A8IHWrtMLtadNXnMTjggvVY8cs.jpg",
    trailer: "https://www.youtube.com/embed/aVZJ-tHtCg4",
    cast: ["種﨑敦美", "市ノ瀬加那", "小林千晃", "岡本信彦", "東地宏樹"],
    releaseDate: "2023-09-29",
    studio: "Madhouse",
    genres: ["Animación", "Acción", "Drama", "Fantasía"],
    rating: 4.3,
  },
  {
    id: 19,
    type: "series",
    title: "Contéstame 1988",
    year: 2015,
    director: "신원호",
    runtime: 90,
    country: "South Korea",
    synopsis:
      "Se centra en los últimos años de la década de los 80. Sung Deok-Sun es una estudiante de secundaria que ha vivido toda su vida en un barrio de Seúl donde compartió su niñez con sus cuatro mejores amigos varones.",
    poster: "https://image.tmdb.org/t/p/w400/lZo7G1kEU70PHP1dCe46I0cUKiF.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: ["이혜리", "류준열", "박보검", "고경표", "이동휘"],
    releaseDate: "2015-11-06",
    studio: "CJ ENM",
    genres: ["Comedia"],
    rating: 4.3,
  },
  {
    id: 20,
    type: "series",
    title: "Avatar: La leyenda de Aang",
    year: 2005,
    director: "Michael Dante DiMartino",
    runtime: 24,
    country: "South Korea",
    synopsis:
      "El mundo está dividido en cuatro naciones correspondientes a los cuatro elementos. En cada generación, sólo un Maestro es capaz de controlar los cuatro elementos, y recibe el nombre de Avatar, el espíritu del mundo manifestado en forma humana.",
    poster: "https://image.tmdb.org/t/p/w400/ucNtkZfpZ6KgxqPo039nN4LAyFR.jpg",
    trailer: "https://www.youtube.com/embed/ooVvH2IYz0w",
    cast: [
      "Zach Tyler Eisen",
      "Mae Whitman",
      "Jack De Sena",
      "Dante Basco",
      "Michaela Jill Murphy",
    ],
    releaseDate: "2005-02-21",
    studio: "Nickelodeon Animation Studio",
    genres: ["Animación", "Acción", "Fantasía"],
    rating: 4.3,
  },
  {
    id: 21,
    type: "series",
    title: "Arcane",
    year: 2021,
    director: "Christian Linke",
    runtime: 0,
    country: "France",
    synopsis:
      "Mientras la discordia separa las ciudades gemelas de Piltóver y Zaun, dos hermanas se enfrentan en una guerra feroz entre tecnologías mágicas y convicciones opuestas.",
    poster: "https://image.tmdb.org/t/p/w400/i1vSPUbiBe2iK2HapGDfHItBFlC.jpg",
    trailer: "https://www.youtube.com/embed/xPKN7MxS8TU",
    cast: ["Hailee Steinfeld", "Ella Purnell"],
    releaseDate: "2021-11-06",
    studio: "Fortiche Production",
    genres: ["Animación", "Acción", "Fantasía"],
    rating: 4.3,
  },
  {
    id: 22,
    type: "series",
    title: "The Pitt",
    year: 2025,
    director: "R. Scott Gemmill",
    runtime: 0,
    country: "United States of America",
    synopsis:
      "El personal del Centro Médico de Traumatismo de Pittsburgh trabaja para salvar vidas en un servicio de urgencias saturado y sin fondos suficientes.",
    poster: "https://image.tmdb.org/t/p/w400/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg",
    trailer: "https://www.youtube.com/embed/dItUVAdJ7Lc",
    cast: [
      "Noah Wyle",
      "Patrick Ball",
      "Katherine LaNasa",
      "Supriya Ganesh",
      "Fiona Dourif",
    ],
    releaseDate: "2025-01-09",
    studio: "John Wells Productions",
    genres: ["Drama"],
    rating: 4.3,
  },
  {
    id: 23,
    type: "series",
    title: "One Piece",
    year: 1999,
    director: "Varios",
    runtime: 24,
    country: "Japan",
    synopsis:
      "Esta historia se sitúa en el momento más álgido de la Gran Era de los Piratas, cuando el joven Monkey D. Luffy quiere llegar a ser el Rey de los Piratas y hacerse al fin con un legendario tesoro, el One Piece.",
    poster: "https://image.tmdb.org/t/p/w400/8f33Q5AuM2G5ZqFeusbIqDjr3cI.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: ["田中真弓", "中井和哉", "矢口真里", "岡村明美", "山口勝平"],
    releaseDate: "1999-10-20",
    studio: "Toei Animation",
    genres: ["Acción", "Comedia", "Animación"],
    rating: 4.3,
  },
  {
    id: 24,
    type: "series",
    title: "Los elegidos",
    year: 2019,
    director: "Dallas Jenkins",
    runtime: 60,
    country: "United States of America",
    synopsis:
      "Narra la vida de Jesucristo y los apóstoles. Ambientada en Judea y Galilea en el siglo I, la serie retrata la vida de Jesús de Nazareth a través de las personas que interactuaron con él.",
    poster: "https://image.tmdb.org/t/p/w400/sADRlqLn9na8p7S1mLWMOU04uit.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Jonathan Roumie",
      "Shahar Isaac",
      "Elizabeth Tabish",
      "Paras Patel",
      "Noah James",
    ],
    releaseDate: "2019-04-21",
    studio: "Loaves & Fishes Productions",
    genres: ["Acción", "Familia", "Drama"],
    rating: 4.3,
  },
  {
    id: 25,
    type: "series",
    title: "Si la vida te da mandarinas...",
    year: 2025,
    director: "임상춘",
    runtime: 0,
    country: "South Korea",
    synopsis:
      "En la isla Jeju, una chica vivaz y un chico leal viven una historia de reveses y triunfos que demuestra que el amor resiste el paso del tiempo.",
    poster: "https://image.tmdb.org/t/p/w400/h3Sv1qMAc6ADS6xWoIrUAzdXarf.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: ["IU", "박보검", "문소리", "박해준"],
    releaseDate: "2025-03-07",
    studio: "Pan Entertainment",
    genres: ["Drama"],
    rating: 4.3,
  },
  {
    id: 26,
    type: "series",
    title: "Más que rivales",
    year: 2025,
    director: "Jacob Tierney",
    runtime: 0,
    country: "Canada",
    synopsis:
      "Dos de las mayores estrellas de la Major League Hockey están unidas por la ambición, la rivalidad y una atracción magnética. Lo que comienza como una aventura secreta entre dos novatos se convierte en un viaje de años de amor, negación y autodescubrimiento.",
    poster: "https://image.tmdb.org/t/p/w400/2y95f1NtLLRM0IIfzHd2hJF6rwk.jpg",
    trailer: "https://www.youtube.com/embed/wSojxn8cAfU",
    cast: ["Hudson Williams", "Connor Storrie", "François Arnaud"],
    releaseDate: "2025-11-28",
    studio: "Accent Aigu Entertainment",
    genres: ["Drama"],
    rating: 4.3,
  },
  {
    id: 27,
    type: "series",
    title: "Chernobyl",
    year: 2019,
    director: "Craig Mazin",
    runtime: 0,
    country: "United Kingdom",
    synopsis:
      "Sigue la verdadera historia de una de las peores catástrofes provocadas por el hombre y habla de los valientes hombres y mujeres que se sacrificaron para salvar a Europa de un desastre inimaginable.",
    poster: "https://image.tmdb.org/t/p/w400/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Jared Harris",
      "Stellan Skarsgård",
      "Emily Watson",
      "Paul Ritter",
      "Jessie Buckley",
    ],
    releaseDate: "2019-05-06",
    studio: "SISTER",
    genres: ["Drama"],
    rating: 4.3,
  },
  {
    id: 28,
    type: "series",
    title: "Fullmetal Alchemist: Brotherhood",
    year: 2009,
    director: "Varios",
    runtime: 25,
    country: "Japan",
    synopsis:
      "La imprudente indiferencia de Edward y Alphonse Elric por las leyes fundamentales de la alquimia les costó caro. Para restaurar lo que se perdió, los hermanos recorren una tierra devastada por la guerra en busca de la Piedra Filosofal.",
    poster: "https://image.tmdb.org/t/p/w400/vIkH7fUQf8Olo8Apq56FQLGDXOo.jpg",
    trailer: "https://www.youtube.com/embed/K0Zip-5kzAE",
    cast: [
      "Romi Park",
      "釘宮理恵",
      "Miki Shin'ichirou",
      "Fumiko Orikasa",
      "高本めぐみ",
    ],
    releaseDate: "2009-04-05",
    studio: "BONES",
    genres: ["Animación", "Acción", "Fantasía", "Drama"],
    rating: 4.3,
  },
  {
    id: 29,
    type: "series",
    title: "Better Call Saul",
    year: 2015,
    director: "Vince Gilligan",
    runtime: 0,
    country: "United States of America",
    synopsis:
      "La acción se ubica en el año 2002 en torno al abogado James Morgan McGill, seis años antes de su aparición en Breaking Bad como Saul Goodman.",
    poster: "https://image.tmdb.org/t/p/w400/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Bob Odenkirk",
      "Jonathan Banks",
      "Rhea Seehorn",
      "Tony Dalton",
      "Giancarlo Esposito",
    ],
    releaseDate: "2015-02-08",
    studio: "Sony Pictures Television",
    genres: ["Crimen", "Drama"],
    rating: 4.3,
  },
  {
    id: 30,
    type: "documentary",
    title: "Nude",
    year: 2017,
    director: "Tony Sacco",
    runtime: 89,
    country: "United States of America",
    synopsis:
      "Un documental sobre la industria de la moda y la fotografía artística que explora la relación entre el arte, el cuerpo y la cultura visual contemporánea.",
    poster: "https://image.tmdb.org/t/p/w400/699DbQ8eTecLmzjTLrao9D5bbpq.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "David Bellemere",
      "Steve Shaw",
      "Rachel Cook",
      "Jessica Clements",
      "Ebonee Davis",
    ],
    releaseDate: "2017-10-29",
    studio: "Starz Entertainment",
    genres: ["Documental"],
    rating: 4.6,
  },
  {
    id: 31,
    type: "documentary",
    title: "Break The Silence: The Movie",
    year: 2020,
    director: "Park Jun-soo",
    runtime: 90,
    country: "South Korea",
    synopsis:
      "Documental que captura la gira mundial de BTS en 2019, mostrando actuaciones en vivo, momentos entre bastidores y la relación entre la banda y sus fans.",
    poster: "https://image.tmdb.org/t/p/w400/kucz66uCOc5vqRXd0xA7YtSUtg4.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: ["RM", "진", "슈가", "제이홉", "지민"],
    releaseDate: "2020-09-10",
    studio: "Big Hit Entertainment",
    genres: ["Música", "Documental"],
    rating: 4.5,
  },
  {
    id: 32,
    type: "documentary",
    title: "Las tres muertes de Marisela Escobedo",
    year: 2020,
    director: "Carlos Pérez Osorio",
    runtime: 109,
    country: "United States of America",
    synopsis:
      "Cuando Rubí, una adolescente de 16 años, es asesinada por su novio en Ciudad Juárez, Marisela Escobedo inicia una cruzada para lograr la captura y el juicio del homicida de su hija.",
    poster: "https://image.tmdb.org/t/p/w400/gYO7mmLti4XtIszP6C7Uc7OQnOc.jpg",
    trailer: "https://www.youtube.com/embed/2vsHHKwqPD8",
    cast: [
      "Juan Manuel Fraire Escobedo",
      "Alejandro Fraire",
      "Blanca Escobedo",
      "Patricia González",
      "Ruth Fierro",
    ],
    releaseDate: "2020-10-14",
    studio: "Scopio",
    genres: ["Documental", "Crimen"],
    rating: 4.4,
  },
  {
    id: 33,
    type: "documentary",
    title: "BTS: Permission to Dance on Stage – LA",
    year: 2022,
    director: "Park Jun-soo",
    runtime: 130,
    country: "South Korea",
    synopsis:
      "La ciudad de Los Ángeles se tiñe de morado con la llegada del concierto de BTS en el SoFi Stadium por primera vez en dos años.",
    poster: "https://image.tmdb.org/t/p/w400/wPZDf3GMMldNcTWnpEiHkte6hYK.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: ["RM", "진", "슈가", "제이홉", "지민"],
    releaseDate: "2022-09-08",
    studio: "HYBE",
    genres: ["Música", "Documental"],
    rating: 4.3,
  },
  {
    id: 34,
    type: "documentary",
    title: "Lady Gaga: The Monster Ball Tour at Madison Square Garden",
    year: 2011,
    director: "Laurieann Gibson",
    runtime: 117,
    country: "United States of America",
    synopsis:
      "Registro del icónico concierto de Lady Gaga en el Madison Square Garden durante su gira The Monster Ball Tour, una de las giras de mayor recaudación de la historia.",
    poster: "https://image.tmdb.org/t/p/w400/o4R7ZyMAatFpCJiT2ELSwfaaCoX.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Lady Gaga",
      "Liza Minnelli",
      "Amanda Balen",
      "Allison Hagendorf",
      "Graham Breitenstein",
    ],
    releaseDate: "2011-05-07",
    studio: "HBO",
    genres: ["Música", "Documental"],
    rating: 4.2,
  },
  {
    id: 35,
    type: "documentary",
    title: "Chivas: La película",
    year: 2018,
    director: "Rubén Bañuelos",
    runtime: 111,
    country: "Mexico",
    synopsis:
      "Un documental que narra los últimos años del famoso C.D. Guadalajara, sus altibajos, victorias y luchas, hasta la llegada de alguien importante que cambiaría el rumbo del club.",
    poster: "https://image.tmdb.org/t/p/w400/go1s43XbczYq84vVwZGCg0IGKKW.jpg",
    trailer: "https://www.youtube.com/embed/6Xo3Jz8JBRY",
    cast: ["Matias Almeyda"],
    releaseDate: "2018-10-25",
    studio: "Cobrafilms",
    genres: ["Documental"],
    rating: 4.2,
  },
  {
    id: 36,
    type: "documentary",
    title: "Nirvana: Unplugged In New York",
    year: 1993,
    director: "Beth McCarthy-Miller",
    runtime: 66,
    country: "United States of America",
    synopsis:
      "Grabación del histórico concierto acústico de Nirvana para el programa MTV Unplugged, considerado uno de los mejores conciertos de la historia del rock.",
    poster: "https://image.tmdb.org/t/p/w400/zLoCBBTdPvGIpZc86wby9dMq3Cz.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Kurt Cobain",
      "Krist Novoselic",
      "Dave Grohl",
      "Pat Smear",
      "Lori Goldston",
    ],
    releaseDate: "1993-12-16",
    studio: "MTV",
    genres: ["Música", "Documental"],
    rating: 4.2,
  },
  {
    id: 37,
    type: "documentary",
    title: "Thriller 40",
    year: 2023,
    director: "Nelson George",
    runtime: 89,
    country: "United States of America",
    synopsis:
      "Este documental rinde homenaje a Thriller de Michael Jackson, el disco más vendido de todos los tiempos. A través de grabaciones nunca antes vistas y entrevistas exclusivas, se cuenta la historia detrás de este icónico álbum.",
    poster: "https://image.tmdb.org/t/p/w400/sBuE1QK9w6KEnigO24EM7ECJ4SM.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "Michael Jackson",
      "Quincy Jones",
      "Paul McCartney",
      "Usher",
      "Mary J. Blige",
    ],
    releaseDate: "2023-12-02",
    studio: "Company Name",
    genres: ["Documental", "Música"],
    rating: 4.2,
  },
  {
    id: 38,
    type: "documentary",
    title: "Rubius X",
    year: 2022,
    director: "Pedro Ample",
    runtime: 75,
    country: "Spain",
    synopsis:
      "Documental que celebra el décimo aniversario de Rubius, uno de los principales creadores de contenidos de España, publicando su primer vídeo.",
    poster: "https://image.tmdb.org/t/p/w400/k6KAAVebtdVb0FRU2PWqYLnhgRA.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: [
      "El Rubius",
      "Miguel Ángel Rogel",
      "Alejandro Bravo Yañez",
      "Abraham Bandera",
      "Irina Isaia",
    ],
    releaseDate: "2022-07-21",
    studio: "Noob Studios",
    genres: ["Documental"],
    rating: 4.2,
  },
  {
    id: 39,
    type: "documentary",
    title: "Selena Gomez: Mi mente y yo",
    year: 2022,
    director: "Alek Keshishian",
    runtime: 95,
    country: "United States of America",
    synopsis:
      "Tras años bajo los reflectores, Selena Gomez alcanza un estrellato pop inimaginable, pero justo cuando llega a una nueva cima, un giro inesperado la arrastra hacia la oscuridad.",
    poster: "https://image.tmdb.org/t/p/w400/kOmjk26BIG54wveOq920JAeaFdG.jpg",
    trailer: "https://www.youtube.com/embed/4MOAbh9eFto",
    cast: [
      "Selena Gómez",
      "Raquelle Stevens",
      "Ashley Cook",
      "Liana Blackburn",
      "Brent L. Boxberger",
    ],
    releaseDate: "2022-11-04",
    studio: "Lighthouse Management + Media",
    genres: ["Documental", "Música"],
    rating: 4.2,
  },
  {
    id: 40,
    type: "documentary",
    title: "Folklore: Sesiones en Long Pond Studio",
    year: 2020,
    director: "Taylor Swift",
    runtime: 106,
    country: "United States of America",
    synopsis:
      "Taylor Swift lleva a los espectadores a las sesiones de grabación de su álbum Folklore, grabado en secreto durante la pandemia, mostrando el proceso creativo detrás de cada canción.",
    poster: "https://image.tmdb.org/t/p/w400/x8gd3v3TNJjq3uzLTuNfKyPQcsD.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: ["Taylor Swift", "Jack Antonoff", "Aaron Dessner", "Justin Vernon"],
    releaseDate: "2020-11-25",
    studio: "Taylor Swift Productions",
    genres: ["Música", "Documental"],
    rating: 4.2,
  },
  {
    id: 41,
    type: "documentary",
    title: "Lil Peep: Everybody's Everything",
    year: 2019,
    director: "Ramez Silyan",
    runtime: 115,
    country: "United States of America",
    synopsis:
      "La íntima historia del ascenso del artista Lil Peep, cuya música desafió los géneros convencionales, atrajo a innumerables fans y terminó definiendo su vida.",
    poster: "https://image.tmdb.org/t/p/w400/xsAfGd8cH5pB8PM3WBkEHNGeDO0.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: ["Lil Peep", "Lil Tracy", "GHOSTEMANE", "Killstation", "Bexey"],
    releaseDate: "2019-11-12",
    studio: "First Access Entertainment",
    genres: ["Documental"],
    rating: 4.2,
  },
  {
    id: 42,
    type: "documentary",
    title: "David Attenborough: Una vida en nuestro planeta",
    year: 2020,
    director: "Alastair Fothergill",
    runtime: 83,
    country: "United Kingdom",
    synopsis:
      "A sus 93 años, David Attenborough ha visitado todos los continentes del planeta. Ahora, por primera vez, reflexiona sobre las experiencias más relevantes de su vida como naturalista.",
    poster: "https://image.tmdb.org/t/p/w400/wA9I2KKUT1moiSnshjTL2QALv3q.jpg",
    trailer: "https://www.youtube.com/embed/aqz-KE-bpKQ",
    cast: ["David Attenborough", "Max Hughes"],
    releaseDate: "2020-09-28",
    studio: "Silverback Films",
    genres: ["Documental", "Drama"],
    rating: 4.2,
  },
];

const Data = {
  all() {
    return CONTENT;
  },
  byId(id) {
    return CONTENT.find((f) => f.id === id) ?? null;
  },
  byType(type) {
    return CONTENT.filter((f) => f.type === type);
  },
  featured(type, n = 4) {
    return Data.byType(type).slice(0, n);
  },
  topRated(type, n = 4) {
    const items = type ? Data.byType(type) : CONTENT;
    return [...items].sort((a, b) => b.rating - a.rating).slice(0, n);
  },
  paginate(items, page = 1, perPage = 8) {
    const total = items.length;
    const totalPages = Math.ceil(total / perPage);
    const start = (page - 1) * perPage;
    return {
      items: items.slice(start, start + perPage),
      page,
      perPage,
      total,
      totalPages,
    };
  },
};
